application: irsite-2013
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /project2
  script: project2.view.app

- url: .*
  script: project1.view.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: lxml
  version: latest
